### ISSUE TITLE
headers sent exception

### ISSUE THREAD

**Issue by willwade** [AceCentre/aacnews#24]
Not sure why this happens:

A new exception has been thrown
Server: lisa
Application: aacinfo
Message:
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    at ServerResponse.res.set.res.header (/srv/aacinfo/node_modules/express/lib/response.js:530:10)
    at ServerResponse.res.json (/srv/aacinfo/node_modules/express/lib/response.js:190:36)
    at /srv/aacinfo/controllers/posts.js:140:13
    at /srv/aacinfo/node_modules/mongoose/lib/query.js:2313:18
    at tryCatcher (/srv/aacinfo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/aacinfo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/srv/aacinfo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/srv/aacinfo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/srv/aacinfo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/srv/aacinfo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/srv/aacinfo/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/srv/aacinfo/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickDomainCallback (node.js:492:13)

**Comment by willwade** [comment]
Looks like a problem with getPosts - and sending the json error once headers already sent..

```
    exec(
      function(err,posts){
        if(err) return res.send(err);
        res.json(posts);
      }
    );
```

**Comment by hosseinamin** [comment]
I have did add some debugging code, So we can get more info when it occurs again.
